# Uniprot #
http://uniprotlabels.bio2rdf.org/sparql

# search_ns_long
CONSTRUCT {
  ?subject ?predicate ?object .
  ?subject ?desc ?taxon .
} WHERE { GRAPH ?graph {
  ?subject ?predicate ?object .
  ?subject ?desc ?taxon .
  FILTER(bif:contains(?object, '"$PARM1$*"')) .
  FILTER(?predicate = rdfs:label)
  FILTER(?desc = <http://bio2rdf.org/m_vocabulary:description>) .
  FILTER(?graph = <http://uniprotlabels.nt> ) .
}} LIMIT 20 OFFSET $PARM2$

#search_ns_short
CONSTRUCT {
  ?subject ?predicate ?object .
  ?subject ?desc ?taxon .
} WHERE { GRAPH ?graph {
  ?subject ?predicate ?object .
  ?subject ?desc ?taxon .
  FILTER(bif:contains(?object, '"beta-lactamase ndm-1"')) .
  FILTER(?predicate = rdfs:label)
  FILTER(?desc = <http://bio2rdf.org/m_vocabulary:description>) .
  FILTER(?graph = <http://uniprotlabels.nt> ) .
}} LIMIT 20 OFFSET 0



# describe 
http://beta.sparql.uniprot.org/sparql


PREFIX up:<http://purl.uniprot.org/core/>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#> 
CONSTRUCT {
  ?prot rdfs:label ?label .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_mnemonic> ?mnemonic .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_gene> ?geneName .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_sequence> ?aa .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_organismUri> ?org .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_organismName> ?taxon .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_isCurated> ?rev .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_hasAnnotation> ?sha .
  ?sha <http://bio2rdf.org/m_vocabulary:uniprot_annotation> ?comment .
  ?sha <http://bio2rdf.org/m_vocabulary:uniprot_annotationType> ?annotationTypeLabel .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_hasClassification> ?class .
  ?class <http://bio2rdf.org/m_vocabulary:uniprot_classification> ?classLabel .
  ?class <http://bio2rdf.org/m_vocabulary:uniprot_classificationCategory> ?classCategory .
  ?prot <http://bio2rdf.org/m_vocabulary:uniprot_hasReference> ?citation .
  ?citation <http://bio2rdf.org/m_vocabulary:uniprot_pubTitle> ?citeTitle .
  ?citation <http://bio2rdf.org/m_vocabulary:uniprot_pubJournal> ?journal .
  ?citation <http://bio2rdf.org/m_vocabulary:uniprot_pubDate> ?citeDate .
}
WHERE
{
  ?prot a up:Protein .
  ?prot rdfs:label ?label .
  ?prot up:mnemonic ?mnemonic .
  ?prot up:sequence ?sequence .
  ?sequence rdf:value ?aa .
  ?prot up:organism ?org .
  ?org up:scientificName ?taxon .
  ?prot up:reviewed ?rev .
  optional {
    ?prot up:encodedBy ?gene .
    ?gene skos:prefLabel ?geneName .
  }
  optional {
    ?prot up:annotation ?sha .
    ?sha rdf:type ?annotationType .
    ?annotationType rdfs:label ?annotationTypeLabel .
    ?sha rdfs:comment ?comment .
  }
  optional {
    ?prot up:classifiedWith ?class .
    ?class skos:prefLabel ?classLabel .
    optional {
      ?class up:category ?classCategoryId .
      ?classCategoryId skos:prefLabel ?classCategory .
    }
  }
  optional {
    ?prot up:citation ?citation .
    ?citation up:title ?citeTitle .
    ?citation up:name ?journal .
    ?citation up:date ?citeDate .
  }
  filter (?prot = <http://purl.uniprot.org/uniprot/C7C422>)
}


select *
where {
  <http://purl.uniprot.org/keywords/862> $p $o
} 


# Pubmed
http://beta.pubmed.bio2rdf.org/sparql

# search_ns

# search_ns
construct {
  ?s rdfs:label ?title .
  ?s <http://bio2rdf.org/m_vocabulary:description> ?journalLabel .
}
where {
  ?s ?p ?o .
  ?o bif:contains '("asthma")' .
  filter (?p = dcterms:title ||
         ?p = dcterms:description) .
  ?s dcterms:title ?title .
  ?s <http://bio2rdf.org/pubmed_vocabulary:journal> ?journal .
  ?journal <http://bio2rdf.org/pubmed_vocabulary:journal_title> ?journalLabel .
} limit 20 offset 0


# describe
construct {
  ?uri rdfs:label ?o .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_author> ?author .
  ?author rdfs:label ?authorName .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_meshterm> ?meshLabel .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_abstract> ?abstractText .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_journalTitle> ?journalLabel .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_publicationDate> ?journalDate .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_journalVolume> ?journalVolume .
  ?uri <http://bio2rdf.org/m_vocabulary:pubmed_journalIssue> ?journalIssue .
} where {
  ?uri rdfs:label ?o .
  optional {
    ?uri dcterms:contributor ?author .
    ?author rdfs:label ?authorName .
  }
  optional {
    ?uri <http://bio2rdf.org/pubmed_vocabulary:mesh_heading> ?mesh .
    ?mesh rdfs:label ?meshLabel .
  }
  optional {
    ?uri dcterms:abstract ?abstract .
    ?abstract dcterms:description ?abstractText .
  }
  optional {
    ?uri <http://bio2rdf.org/pubmed_vocabulary:journal> ?journal .
    ?journal rdfs:label ?journalLabel .
    optional {
      ?journal <http://bio2rdf.org/pubmed_vocabulary:publication_date> ?journalDate .
    }
    optional {
      ?journal <http://bio2rdf.org/pubmed_vocabulary:journal_volume> ?journalVolume .
      ?journal <http://bio2rdf.org/pubmed_vocabulary:issue> ?journalIssue .
    }
  }
  filter (?uri = <http://bio2rdf.org/pubmed:19770275>)
}


# Ontobee (obo ontologies)
http://sparql.hegroup.org/sparql

# GO

CONSTRUCT {
  ?subject rdfs:label ?object .
  ?subject <http://bio2rdf.org/m_vocabulary:description> ?subject .
} WHERE { GRAPH ?graph {
  ?subject ?predicate ?object .
  ?subject <http://www.geneontology.org/formats/oboInOwl#hasOBONamespace> ?description .
  FILTER(bif:contains(?object, '"$PARM1$*"')) .
  FILTER(?graph = <http://purl.obolibrary.org/obo/merged/GO> ) .
  FILTER((?predicate = <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym>) OR (?predicate = rdfs:label) OR (?predicate = <http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym>)) .
}}limit 20 offset $PARM2$

## wiki enrichment

### get wiki img
construct {
  ?s foaf:depiction ?o
}
where {
  ?s foaf:depiction ?o .
  ?s <http://dbpedia.org/property/goCode> "$PARM1$"^^xsd:integer .
}

### get wiki complete graph
construct {
  ?s ?p ?o
}
where {
  ?s ?p ?o .
  ?s <http://dbpedia.org/property/goCode> "$PARM1$"^^xsd:integer .
}


## Generic Wiki based on Label

# image
construct {
<$URI$> foaf:depiction ?image
}
where {
<$URI$> foaf:depiction ?image
}

construct {
<http://dbpedia.org/resource/Serotonin> foaf:depiction ?image
}
where {
<http://dbpedia.org/resource/Serotonin> foaf:depiction ?image
}

# all graph
construct {
<$URI$> ?p ?o .
}
where {
<$URI$> ?p ?o .
}




# CHEBI

CONSTRUCT {
  ?subject rdfs:label ?object .
  ?subject <http://bio2rdf.org/m_vocabulary:description> ?subject .
} WHERE { GRAPH ?graph {
  ?subject ?predicate ?object .
  ?subject <http://www.geneontology.org/formats/oboInOwl#hasOBONamespace> ?description .
  FILTER(bif:contains(?object, '"$PARM1$*"')) .
  FILTER(?graph = <http://purl.obolibrary.org/obo/merged/CHEBI> ) .
  FILTER((?predicate = <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym>) OR (?predicate = rdfs:label) OR (?predicate = <http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym>)) .
}}limit 20 offset $PARM2$

### get wiki img
construct {
  ?s foaf:depiction ?o
}
where {
  ?s foaf:depiction ?o .
  ?s <http://dbpedia.org/property/chebi> "$PARM1$"^^xsd:integer .
}

### get wiki complete graph
construct {
  ?s ?p ?o
}
where {
  ?s ?p ?o .
  ?s <http://dbpedia.org/property/chebi> "$PARM1$"^^xsd:integer .
}



# DOID
CONSTRUCT {
  ?subject rdfs:label ?object .
  ?subject <http://bio2rdf.org/m_vocabulary:description> ?subject .
} WHERE { GRAPH ?graph {
  ?subject ?predicate ?object .
  ?subject <http://www.geneontology.org/formats/oboInOwl#hasOBONamespace> ?description .
  FILTER(bif:contains(?object, '"$PARM1$*"')) .
  FILTER(?graph = <http://purl.obolibrary.org/obo/merged/DOID> ) .
  FILTER((?predicate = <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym>) OR (?predicate = rdfs:label) OR (?predicate = <http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym>)) .
}}limit 20 offset $PARM2$

# describe chebi- need to manage subClassOf
construct
{
  <http://purl.obolibrary.org/obo/CHEBI_28790> ?p ?o .
  <http://purl.obolibrary.org/obo/CHEBI_28790> ?p2 ?o2 .
} where 
{
  <http://purl.obolibrary.org/obo/CHEBI_28790> ?p ?o .
  optional{
    <http://purl.obolibrary.org/obo/CHEBI_28790> ?p2 ?o2 .
    filter ()
  }
} 

# DrugBank
http://drugbank.bio2rdf.org/sparql

# search_ns
CONSTRUCT {
?s rdfs:label ?label
}
WHERE {
 {
   SELECT ?s rdfs:label str($o) AS ?label
   WHERE {
    ?s rdfs:label ?o .
    ?s a ?type .
    ?o bif:contains '"?PARM1?*"' .
    FILTER (?type = <http://bio2rdf.org/drugbank_vocabulary:Drug>) .
   }
 }
}LIMIT 20 OFFSET $PARM2$



# DBpedia

http://dbpedia.org/sparql

# go 

select *
where {
$s foaf:depiction $o .
$s <http://dbpedia.org/property/goCode> 4396 .
}

describe <http://dbpedia.org/resource/Hexokinase>

